fint:
  org-id: ofk.no
  application-id: fint-kontroll-resource-factory
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}
    default-replicas: 1
  kontroll:
    user:
      publishing:
        initial-delay: 5000
        initial-delay-elev: 250000
        fixed-delay: 20000
    resource:
      publishing:
        initial-delay-application-resource-location: 60000
        fixed-delay: 250000
      license-enforcement:
        hard-stop: 1
        floating: 3
        free-all: 2
        free-edu:
        free-student:
      valid-roles-for-usertype:
        student: cc6d98652b30fefacaa8787e,5b13297615105560b150c373,df359d76c6069854225737cc,169c03dc8d0d7c7566ce0da9
        employee-staff: abe40447ab2f0a18fa00d931,f8bb90c80eefa1a7b8ed8a5e,df359d76c6069854225737cc,169c03dc8d0d7c7566ce0da9
        employee-faculty: 46b8d74396df230071abc30a,5b13297615105560b150c373,f8bb90c80eefa1a7b8ed8a5e,df359d76c6069854225737cc,169c03dc8d0d7c7566ce0da9
        all-types: df359d76c6069854225737cc,169c03dc8d0d7c7566ce0da9
spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
  profiles:
    include:
      - observability
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN