fint:
  org-id: ofk.no
  application-id: fint-kontroll-resource-factory
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}
    default-replicas: 1
  kontroll:
    user:
      publishing:
        initial-delay: 20000
        initial-delay-elev: 25000
        fixed-delay: 20000
    resource:
      license-enforcement:
        hard-stop: 1
        floating: 3
        free-all: 2
        free-edu:
        free-student:
      valid-roles-for-usertype:
        student: 1
        employee-staff: 2
        employee-faculty: 3

spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
  profiles:
    include:
      - observability
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN