fint:
  org-id: fintlabs.no
  client:
    base-url: https://beta.felleskomponent.no
  kafka:
    default-replicas: 1
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
  kontroll:
    user:
      publishing:
        initial-delay: 10000
        initial-delay-elev: 25000
        fixed-delay: 20000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8092
logging:
  level:
    #no.fintlabs.user.UserPublishingComponent: DEBUG
    no.fintlabs: INFO
