apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-resource-factory
  app.kubernetes.io/instance: fint-kontroll-resource-factory_afk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: afk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "afk-no-fint-kontroll-resource-factory"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "afk-no.kontroll.*"
    target:
      kind: Application
      name: fint-kontroll-resource-factory


