apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-resource-factory
  app.kubernetes.io/instance: fint-kontroll-resource-factory_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/env/0/value"
        value: "fint-kontroll-resource-factory"
      - op: replace
        path: "/spec/env/1/value"
        value: "3"
      - op: replace
        path: "/spec/env/2/value"
        value: "3"
      - op: replace
        path: "/spec/env/3/value"
        value: "1"
      - op: replace
        path: "/spec/env/4/value"
        value: ""
      - op: replace
        path: "/spec/env/5/value"
        value: ""
      - op: replace
        path: "/spec/env/6/value"
        value: "1"
      - op: replace
        path: "/spec/env/7/value"
        value: "2"
      - op: replace
        path: "/spec/env/8/value"
        value: "3"
      - op: replace
        path: "/spec/env/9/value"
        value: ""

    target:
      kind: Application
      name: fint-kontroll-resource-factory


