apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-resource-factory
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-resource-factory:latest
  imagePullPolicy: Always
  env:
      - name: spring.kafka.consumer.group-id
        value: 'fint-kontroll-resource-factory'
      - name: fint.kontroll.resource.license-enforcement.hard-stop
        value: 'list of all license model ids that should be hard-stopped'
      - name: fint.kontroll.resource.license-enforcement.floating
        value: 'list of all license model ids that should be floating'
      - name: fint.kontroll.resource.license-enforcement.free-all
        value: 'list of all license model ids that should be free for all'
      - name: fint.kontroll.resource.license-enforcement.free-edu
        value: 'list of all license model ids that should be free for educational purposes'
      - name: fint.kontroll.resource.license-enforcement.free-student
        value: 'list of all license model ids that should be free for students'
      - name: fint.kontroll.resource.valid-roles-for-usertype.student
        value: 'list of all external usertype ids that should be mapped to usertype student'
      - name: fint.kontroll.resource.valid-roles-for-usertype.employee-staff
        value: 'list of all external usertype ids that should be mapped to usertype employee-staff'
      - name: fint.kontroll.resource.valid-roles-for-usertype.employee-faculty
        value: 'list of all external usertype ids that should be mapped to usertype employee-faculty'
      - name: fint.kontroll.resource.valid-roles-for-usertype.all-types
        value: 'list of all external usertype ids that should be mapped to usertype all-types'

  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
